# Generated by Django 5.2.13 on 2026-05-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='waste_type',
            field=models.CharField(blank=True, choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('glass', 'Glass'), ('metal', 'Metal'), ('organic', 'Organic'), ('mixed', 'Mixed')], max_length=20, null=True),
        ),
    ]
