# Generated by Django 5.2.13 on 2026-05-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_waste_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingsession',
            name='step_1_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='step_2_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='step_3_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='step_4_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='step_5_completed',
            field=models.BooleanField(default=False),
        ),
    ]
