# Generated by Django 5.2.13 on 2026-06-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingsession',
            name='current_step',
            field=models.IntegerField(default=1),
        ),
    ]
