# Generated by Django 5.2.13 on 2026-05-07 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_onboardingsession_step_1_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardnotificationqueue',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='rewardnotificationqueue',
            name='queued_at',
        ),
        migrations.RemoveField(
            model_name='rewardnotificationqueue',
            name='status',
        ),
        migrations.RemoveField(
            model_name='rewardnotificationqueue',
            name='user',
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
