# Generated by Django 5.2.13 on 2026-05-15 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationCodeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_used', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('invalid_attempt', 'Invalid Attempt')], max_length=20)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('points_credited', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('attempted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_logs', to='pickup.pickuprequest')),
            ],
        ),
    ]
