# Generated by Django 5.2.13 on 2026-05-20 03:55

import django.db.models.deletion
import marketplace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('glass', 'Glass'), ('metal', 'Metal'), ('organic', 'Organic')], max_length=20, unique=True)),
                ('min_price_per_kg', models.FloatField()),
                ('max_price_per_kg', models.FloatField()),
                ('suggested_price_per_kg', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='V-Martins Lagos Market 2026', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('current_menu', models.CharField(default='main', max_length=50)),
                ('session_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('glass', 'Glass'), ('metal', 'Metal'), ('organic', 'Organic')], max_length=20)),
                ('quantity_kg', models.FloatField()),
                ('price_per_kg', models.FloatField()),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('channel', models.CharField(choices=[('app', 'App'), ('ussd', 'USSD'), ('whatsapp', 'WhatsApp')], default='app', max_length=20)),
                ('expires_at', models.DateTimeField(default=marketplace.models.default_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.FloatField()),
                ('total_paid', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketplace.materiallisting')),
            ],
        ),
    ]
