# Generated by Django 5.2.13 on 2026-06-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('glass', 'Glass'), ('metal', 'Metal'), ('organic', 'Organic'), ('ewaste', 'Ewaste')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('sorting_guide', models.TextField()),
                ('tips', models.TextField(blank=True)),
                ('track', models.CharField(choices=[('household', 'Household Only'), ('collector', 'Collector Only'), ('all', 'All Users')], default='all', max_length=20)),
                ('collector_module_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GUIDE_VIEWED', 'Guide Viewed'), ('QUIZ_ANSWERED', 'Quiz Answered'), ('BADGE_AWARDED', 'Badge Awarded'), ('EWASTE_DISPOSAL_QUERY', 'Ewaste Disposal Query')], max_length=30)),
                ('module_id', models.CharField(max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('pidgin', 'Pidgin')], default='en', max_length=10)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('USSD', 'USSD'), ('MOBILE_APP', 'Mobile App')], default='MOBILE_APP', max_length=20)),
                ('guide_completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('guide_section_ref', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('badge_awarded', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('none', 'None'), ('plastic_complete', 'Plastic Complete'), ('glass_complete', 'Glass Complete'), ('metal_complete', 'Metal Complete'), ('paper_complete', 'Paper Complete'), ('organic_complete', 'Organic Complete'), ('ewaste_complete', 'Ewaste Complete'), ('full_sorter', 'Full Sorter'), ('metal_collector', 'Metal Collector'), ('organic_collector', 'Organic Collector'), ('ewaste_collector', 'Ewaste Collector'), ('full_collector', 'Full Collector')], default='none', max_length=20)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEducationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastic_guide_read', models.BooleanField(default=False)),
                ('glass_guide_read', models.BooleanField(default=False)),
                ('metal_guide_read', models.BooleanField(default=False)),
                ('paper_guide_read', models.BooleanField(default=False)),
                ('organic_guide_read', models.BooleanField(default=False)),
                ('ewaste_guide_read', models.BooleanField(default=False)),
                ('plastic_quiz_passed', models.BooleanField(default=False)),
                ('glass_quiz_passed', models.BooleanField(default=False)),
                ('metal_quiz_passed', models.BooleanField(default=False)),
                ('paper_quiz_passed', models.BooleanField(default=False)),
                ('organic_quiz_passed', models.BooleanField(default=False)),
                ('ewaste_quiz_passed', models.BooleanField(default=False)),
                ('plastic_badge_earned', models.BooleanField(default=False)),
                ('glass_badge_earned', models.BooleanField(default=False)),
                ('metal_badge_earned', models.BooleanField(default=False)),
                ('paper_badge_earned', models.BooleanField(default=False)),
                ('organic_badge_earned', models.BooleanField(default=False)),
                ('ewaste_badge_earned', models.BooleanField(default=False)),
                ('full_sorter_badge_earned', models.BooleanField(default=False)),
                ('full_collector_badge_earned', models.BooleanField(default=False)),
                ('daily_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('separation_method_informed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
