# Generated by Django 5.2.13 on 2026-06-10 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='collector_module_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='track',
            field=models.CharField(choices=[('household', 'Household Only'), ('collector', 'Collector Only'), ('all', 'All Users')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='guide_section_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('glass', 'Glass'), ('metal', 'Metal'), ('organic', 'Organic'), ('ewaste', 'Ewaste')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='badge_awarded',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('none', 'None'), ('plastic_complete', 'Plastic Complete'), ('glass_complete', 'Glass Complete'), ('metal_complete', 'Metal Complete'), ('paper_complete', 'Paper Complete'), ('organic_complete', 'Organic Complete'), ('ewaste_complete', 'Ewaste Complete'), ('full_sorter', 'Full Sorter'), ('metal_collector', 'Metal Collector'), ('organic_collector', 'Organic Collector'), ('ewaste_collector', 'Ewaste Collector'), ('full_collector', 'Full Collector')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='EducationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GUIDE_VIEWED', 'Guide Viewed'), ('QUIZ_ANSWERED', 'Quiz Answered'), ('BADGE_AWARDED', 'Badge Awarded'), ('EWASTE_DISPOSAL_QUERY', 'Ewaste Disposal Query')], max_length=30)),
                ('module_id', models.CharField(max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('pidgin', 'Pidgin')], default='en', max_length=10)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('USSD', 'USSD'), ('MOBILE_APP', 'Mobile App')], default='MOBILE_APP', max_length=20)),
                ('guide_completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserEducationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastic_guide_read', models.BooleanField(default=False)),
                ('glass_guide_read', models.BooleanField(default=False)),
                ('metal_guide_read', models.BooleanField(default=False)),
                ('paper_guide_read', models.BooleanField(default=False)),
                ('organic_guide_read', models.BooleanField(default=False)),
                ('ewaste_guide_read', models.BooleanField(default=False)),
                ('plastic_quiz_passed', models.BooleanField(default=False)),
                ('glass_quiz_passed', models.BooleanField(default=False)),
                ('metal_quiz_passed', models.BooleanField(default=False)),
                ('paper_quiz_passed', models.BooleanField(default=False)),
                ('organic_quiz_passed', models.BooleanField(default=False)),
                ('ewaste_quiz_passed', models.BooleanField(default=False)),
                ('plastic_badge_earned', models.BooleanField(default=False)),
                ('glass_badge_earned', models.BooleanField(default=False)),
                ('metal_badge_earned', models.BooleanField(default=False)),
                ('paper_badge_earned', models.BooleanField(default=False)),
                ('organic_badge_earned', models.BooleanField(default=False)),
                ('ewaste_badge_earned', models.BooleanField(default=False)),
                ('full_sorter_badge_earned', models.BooleanField(default=False)),
                ('full_collector_badge_earned', models.BooleanField(default=False)),
                ('daily_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('separation_method_informed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
